/**
 * Side Panel Logic (panel.js) - EXTREME STABILITY VERSION
 */

document.addEventListener("DOMContentLoaded", () => {
  const getEl = (id) => document.getElementById(id);
  
  const analyzeBtn = getEl("analyze-btn");
  const urlEl = getEl("current-url");
  const statusMessage = getEl("status-message");
  const resultsArea = getEl("results-area");
  const copyAllBtn = getEl("copy-all-btn");
  const downloadZipBtn = getEl("download-zip-btn");
  let lastResult = null;

  updateCurrentUrl();

  if (analyzeBtn) {
    analyzeBtn.addEventListener("click", async () => {
      const btnLabel = analyzeBtn.querySelector(".btn-label");
      if (analyzeBtn.disabled) return;

      try {
        analyzeBtn.disabled = true;
        if (btnLabel) btnLabel.innerText = "Analyzing Site...";
        showStatus("Step 1/2: Extracting Site DNA...", "info");
        
        const dataResponse = await chrome.runtime.sendMessage({ action: "GET_PAGE_DATA" });
        if (dataResponse.error) throw new Error(dataResponse.error);
        
        showStatus("Step 2/2: Mapping Architectural Realism...", "info");
        const aiResponse = await chrome.runtime.sendMessage({ 
          action: "GENERATE_PROMPT", 
          data: dataResponse.data 
        });

        if (aiResponse.error) throw new Error(aiResponse.error);
        renderResults(aiResponse.result);
      } catch (err) {
        showError(err.message);
      } finally {
        analyzeBtn.disabled = false;
        if (btnLabel) btnLabel.innerText = "Analyze This Site";
      }
    });
  }

  if (copyAllBtn) {
    copyAllBtn.addEventListener("click", () => {
      if (!lastResult) return;
      const r = lastResult;
      const report = `
SITECLONE AI - RECONSTRUCTION REPORT
🌐 SOURCE: ${urlEl?.innerText || 'Web'}
📊 ARCHITECTURE: ${r.siteType} | ${r.designStyle}
📋 CLONE PROMPT: ${r.clonePrompt}
Generated by SiteClone AI`.trim();
      copyToClipboard(report, copyAllBtn);
    });
  }

  if (downloadZipBtn) {
    downloadZipBtn.addEventListener("click", async () => {
      if (!lastResult || typeof JSZip === 'undefined') {
        showStatus("Analyzing site first...", "error");
        return;
      }
      
      try {
        const zip = new JSZip();
        // ESCAPE BACKTICKS TO PREVENT SYNTAX ERRORS IN TEMPLATES
        const r = {
          ...lastResult,
          clonePrompt: (lastResult.clonePrompt || '').replace(/`/g, "'"),
          starterTemplate: (lastResult.starterTemplate || '').replace(/`/g, "'")
        };
        
        const folder = zip.folder("SiteBlueprint-Project");

        // 1. MASTER BLUEPRINT
        folder.file("README-MASTER.md", `# 🏗️ MASTER BLUEPRINT - ${r.siteType}\n\n## Expert Prompt (Paste this into Claude/GPT-4o):\n\`\`\`\n${r.clonePrompt}\n\`\`\`\n\n## Multi-Page Strategy:\n${r.multiPageStrategy || "Analyze internal links and replicate the layout logic across all routes."}`);

        // 2. DOCUMENTATION FOLDER
        const docs = folder.folder("docs");
        docs.file("SITEMAP.md", `# Site Map Analysis\nNavigation Items Detected:\n${(r.navigationItems || []).map(i => `- ${i.text} (${i.href})`).join('\n')}`);
        
        const prompts = docs.folder("component-prompts");
        Object.entries(r.componentPrompts || {}).forEach(([name, logic]) => {
          prompts.file(`${name}-Logic.txt`, logic);
        });

        // 3. index.html - LIVE SKELETON
        const primary = r.colorPalette[0] || "#6366f1";
        const font = (r.fonts || ["Inter"])[0];
        const html = `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><title>Blueprint: ${r.siteType}</title><script src="https://cdn.tailwindcss.com"></script><style>@import url('https://fonts.googleapis.com/css2?family=${font.replace(/\s+/g, '+')}:wght@700;900&display=swap');body{font-family:'${font}',sans-serif;}</style></head><body class="bg-black text-white selection:bg-indigo-500">${r.starterTemplate}</body></html>`;
        folder.file("index.html", html);

        // 4. TAILWIND & CONFIG
        folder.file("tailwind.config.js", `module.exports = { theme: { extend: { colors: { primary: '${primary}', secondary: '${r.colorPalette[1] || '#4f46e5'}' } } } }`);

        const content = await zip.generateAsync({ type: "blob" });
        const reader = new FileReader();
        reader.onload = function() {
          const base64 = reader.result.split(',')[1];
          chrome.downloads.download({
            url: 'data:application/zip;base64,' + base64,
            filename: `SiteBlueprint-${r.siteType.replace(/\s+/g, '-')}.zip`,
            saveAs: true
          });
        };
        reader.readAsDataURL(content);
        
        const orig = downloadZipBtn.innerHTML;
        downloadZipBtn.innerText = "EXPORTED!";
        setTimeout(() => downloadZipBtn.innerHTML = orig, 2000);
      } catch (err) {
        console.error("Zip Error:", err);
        showError("ZIP generation failed. Copy the prompt instead.");
      }
    });
  }

  function normalizeResult(raw) {
    const l = {};
    for (let k in raw) l[k.toLowerCase()] = raw[k];
    const s = l.summary || {};
    const sl = {};
    for (let k in s) sl[k.toLowerCase()] = s[k];
    const ts = l.techstack || l.techstack || {};
    const tsl = {};
    for (let k in ts) tsl[k.toLowerCase()] = ts[k];

    return {
      siteType: sl.sitetype || sl.sitetype || "Architectural Model",
      designStyle: sl.designstyle || sl.designstyle || "High-End",
      complexity: sl.complexity || "High",
      estimatedBuildTime: sl.estimatedbuildtime || "Unknown",
      clonePrompt: l.cloneprompt || l.cloneprompt || "",
      multiPageStrategy: l.multipagestrategy || l.multiPageStrategy || "",
      componentPrompts: l.componentprompts || l.componentPrompts || {},
      navigationItems: l.navigationitems || l.navigationItems || [],
      starterTemplate: l.startertemplate || l.startertemplate || "",
      techStack: {
        frontend: tsl.frontend || "Next.js",
        styling: tsl.styling || "Tailwind CSS",
        animations: tsl.animations || "Framer Motion",
        extras: tsl.extras || []
      },
      roadmap: l.roadmap || [],
      colorPalette: l.colorpalette || l.colorpalette || ["#6366f1", "#4f46e5", "#000"],
      fonts: l.fonts || ["Outfit"]
    };
  }

  function renderResults(raw) {
    try {
      lastResult = normalizeResult(raw);
      const r = lastResult;
      getEl('site-type').innerText = r.siteType;
      getEl('design-style').innerText = r.designStyle;
      getEl('complexity').innerText = r.complexity;
      getEl('build-time').innerText = r.estimatedBuildTime;
      getEl('clone-prompt-text').innerText = r.clonePrompt;
      
      const tc = getEl("tech-stack-list");
      if (tc) {
        tc.innerHTML = "";
        [r.techStack.frontend, r.techStack.styling, r.techStack.animations].forEach(i => {
          const t = document.createElement("span"); t.className="tech-tag"; t.innerText=i; tc.appendChild(t);
        });
      }

      const rm = getEl("roadmap-list");
      if (rm) {
        rm.innerHTML = "";
        r.roadmap.forEach(s => {
          const d = document.createElement("div"); d.className="step-card";
          d.innerHTML=`<div class="step-num">${s.step||'?'}</div><div class="step-info"><h4>${s.task||'Task'}</h4><p>${s.detail||'...'}</p><span>${s.time||''}</span></div>`;
          rm.appendChild(d);
        });
      }

      const cp = getEl("color-palette");
      if (cp) {
        cp.innerHTML = "";
        r.colorPalette.slice(0, 6).forEach(c => {
          const s = document.createElement("div"); s.className="swatch";
          s.innerHTML=`<div class="swatch-circle" style="background-color: ${c}"></div><span class="swatch-hex">${c}</span>`;
          cp.appendChild(s);
        });
      }
      hideStatus();
      if (resultsArea) resultsArea.classList.remove("hidden");
    } catch (e) { showError("Loaded with minor parsing issues."); resultsArea.classList.remove("hidden"); }
  }

  function copyToClipboard(text, btn) {
    navigator.clipboard.writeText(text).then(() => {
      const o = btn.innerHTML; btn.innerText = "COPIED!"; setTimeout(() => btn.innerHTML=o, 2000);
    });
  }

  function updateCurrentUrl() {
    chrome.tabs.query({ active: true, currentWindow: true }, (tabs) => {
      if (tabs[0]?.url && urlEl) {
        try { urlEl.innerText = new URL(tabs[0].url).hostname; } catch(e) { urlEl.innerText = "Browser"; }
      }
    });
  }

  function showStatus(msg, type) { if (statusMessage) { statusMessage.innerText = msg; statusMessage.classList.remove("hidden"); } }
  function showError(msg) { if (statusMessage) { statusMessage.innerHTML = msg; statusMessage.classList.remove("hidden"); } }
  function hideStatus() { if (statusMessage) statusMessage.classList.add("hidden"); }
});
