/**
 * UI Logic for the Side Panel (V3 Refined)
 */

document.addEventListener("DOMContentLoaded", () => {
  const getEl = (id) => document.getElementById(id);

  const analyzeBtn = getEl("analyze-btn");
  const refreshBtn = getEl("refresh-btn");
  const copyBtn = getEl("copy-btn");
  const urlEl = getEl("current-url");
  const statusMessage = getEl("status-message");
  const resultsArea = getEl("results-area");
  const copyAllBtn = getEl("copy-all-btn");
  let lastResult = null;

  // Initialize URL display
  updateCurrentUrl();

  // Listen for tab changes
  chrome.tabs.onActivated.addListener(updateCurrentUrl);
  chrome.tabs.onUpdated.addListener(updateCurrentUrl);

  if (refreshBtn) {
    refreshBtn.addEventListener("click", () => {
      chrome.tabs.query({ active: true, currentWindow: true }, (tabs) => {
        if (tabs[0]) chrome.tabs.reload(tabs[0].id);
      });
    });
  }

  if (analyzeBtn) {
    analyzeBtn.addEventListener("click", () => {
      analyzeBtn.disabled = true;
      if (resultsArea) resultsArea.classList.add("hidden");
      showStatus("Analyzing website structure...", "info");
      
      // 1. Get Page Data
      chrome.runtime.sendMessage({ action: "GET_PAGE_DATA" }, (response) => {
        if (response && response.error) {
          showError(response.error);
          resetUI();
          return;
        }

        if (response && response.data) {
          showStatus("Generating clone prompt...", "info");
          
          // 2. Generate Prompt via AI
          chrome.runtime.sendMessage({ action: "GENERATE_PROMPT", data: response.data }, (aiResponse) => {
            if (aiResponse && aiResponse.error) {
              showError(aiResponse.error);
              resetUI();
              return;
            }

            if (aiResponse && aiResponse.result) {
              renderResults(aiResponse.result);
              hideStatus();
              if (resultsArea) resultsArea.classList.remove("hidden");
            }
            resetUI();
          });
        }
      });
    });
  }

  if (copyBtn) {
    copyBtn.addEventListener("click", () => {
      const promptText = getEl("clone-prompt-text");
      if (promptText) {
        copyToClipboard(promptText.innerText, copyBtn);
      }
    });
  }

  if (copyAllBtn) {
    copyAllBtn.addEventListener("click", () => {
      if (!lastResult) return;
      
      const formattedReport = `
SITECLONE AI - RECONSTRUCTION REPORT
------------------------------------
🌐 SOURCE: ${urlEl.innerText}
📊 SUMMARY:
- Type: ${lastResult.summary.siteType}
- Design Style: ${lastResult.summary.designStyle}
- Complexity: ${lastResult.summary.complexity}
- Build Time: ${lastResult.summary.estimatedBuildTime}

📋 CLONE PROMPT (FOR AI RECONSTRUCTION):
${lastResult.clonePrompt}

⚙️ SUGGESTED TECH STACK:
- Frontend: ${lastResult.techStack.frontend}
- Styling: ${lastResult.techStack.styling}
- Animations: ${lastResult.techStack.animations}
- State: ${lastResult.techStack.stateManagement}
- Hosting: ${lastResult.techStack.hosting}
- Extras: ${(lastResult.techStack.extras || []).join(', ')}

🗺️ IMPLEMENTATION ROADMAP:
${lastResult.roadmap.map(s => `${s.step}. ${s.task}: ${s.detail} (${s.time})`).join('\n')}

🎨 COLORS: ${(lastResult.colorPalette || []).join(' ')}
🔤 FONTS: ${(lastResult.fonts || []).join(', ')}

Generated by SiteClone AI
------------------------------------`.trim();

      copyToClipboard(formattedReport, copyAllBtn);
    });
  }

  function copyToClipboard(text, btn) {
    navigator.clipboard.writeText(text).then(() => {
      const originalText = btn.innerHTML;
      btn.innerText = "COPIED!";
      setTimeout(() => btn.innerHTML = originalText, 2000);
    });
  }

  function updateCurrentUrl() {
    chrome.tabs.query({ active: true, currentWindow: true }, (tabs) => {
      if (tabs.length > 0 && tabs[0].url && urlEl) {
        try {
          const url = new URL(tabs[0].url);
          urlEl.innerText = url.hostname;
        } catch (e) {
          urlEl.innerText = "Internal Page";
        }
      }
    });
  }

  function renderResults(res) {
    lastResult = res; // Store for copy-all
    // Summary
    const fields = {
      'site-type': res.summary.siteType,
      'design-style': res.summary.designStyle,
      'complexity': res.summary.complexity,
      'build-time': res.summary.estimatedBuildTime,
      'clone-prompt-text': res.clonePrompt
    };

    Object.entries(fields).forEach(([id, val]) => {
      const el = getEl(id);
      if (el) el.innerText = val;
    });

    // Tech Stack
    const techContainer = getEl("tech-stack-list");
    if (techContainer) {
      techContainer.innerHTML = "";
      const stack = res.techStack;
      const items = [stack.frontend, stack.styling, stack.animations, stack.cms, stack.hosting, ...(stack.extras || [])];
      items.filter(Boolean).forEach(item => {
        const tag = document.createElement("span");
        tag.className = "tech-tag";
        tag.innerText = item;
        techContainer.appendChild(tag);
      });
    }

    // Roadmap
    const roadMapContainer = getEl("roadmap-list");
    if (roadMapContainer) {
      roadMapContainer.innerHTML = "";
      res.roadmap.forEach(step => {
        const stepEl = document.createElement("div");
        stepEl.className = "step-card";
        stepEl.innerHTML = `
          <div class="step-num">${step.step}</div>
          <div class="step-info">
            <h4>${step.task}</h4>
            <p>${step.detail}</p>
            <span class="step-time">${step.time}</span>
          </div>
        `;
        roadMapContainer.appendChild(stepEl);
      });
    }

    // Colors
    const palette = getEl("color-palette");
    if (palette) {
      palette.innerHTML = "";
      (res.colorPalette || []).slice(0, 6).forEach(color => {
        const swatch = document.createElement("div");
        swatch.className = "swatch";
        swatch.innerHTML = `
          <div class="swatch-circle" style="background-color: ${color}"></div>
          <span class="swatch-hex">${color}</span>
        `;
        palette.appendChild(swatch);
      });
    }

    // Fonts
    const fontsContainer = getEl("fonts-container");
    if (fontsContainer) {
      fontsContainer.innerHTML = "";
      (res.fonts || []).forEach(font => {
        const tag = document.createElement("span");
        tag.className = "tech-tag";
        tag.innerText = font;
        fontsContainer.appendChild(tag);
      });
    }
  }

  function showStatus(msg, type) {
    if (!statusMessage) return;
    statusMessage.innerText = msg;
    statusMessage.classList.remove("hidden", "status-error");
    if (type === "error") statusMessage.classList.add("status-error");
  }

  function showError(msg) {
    if (!statusMessage) return;
    statusMessage.innerHTML = typeof msg === 'string' && msg.includes("options") ? 
      `<span>${msg} <a href="#" id="open-options" style="color:#6366f1; text-decoration:underline; font-weight:600;">Options Page</a></span>` : 
      msg;
    statusMessage.classList.remove("hidden");
    
    const openOptionsLink = getEl("open-options");
    if (openOptionsLink) {
      openOptionsLink.addEventListener("click", (e) => {
        e.preventDefault();
        chrome.runtime.openOptionsPage();
      });
    }
  }

  function hideStatus() {
    if (statusMessage) statusMessage.classList.add("hidden");
  }

  function resetUI() {
    if (analyzeBtn) analyzeBtn.disabled = false;
  }
});
